# Generated by Django 5.1.7 on 2025-03-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='usuario_atribuido',
        ),
        migrations.AlterField(
            model_name='task',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
