# Generated by Django 5.1.7 on 2025-03-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_usuario_atribuido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='pendente', max_length=20),
        ),
    ]
